---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade installed packages (no dist-upgrade)
  ansible.builtin.apt:
    upgrade: yes

- name: Install common applications
  ansible.builtin.apt:
    name: "{{ common_packages }}"
    state: present
